#!/usr/bin/env bash
set -euo pipefail

WS="/home/jabbit/.openclaw/workspace"
DATE="$(date -u +%Y-%m-%d)"
OUT="$WS/docs/self-improvement-$DATE.md"

COMMITS=$(git -C "$WS" log --since='24 hours ago' --pretty=format:'- %h %s' | sed -n '1,20p' || true)

cat > "$OUT" <<EOF
# SELF-IMPROVEMENT LOG — $DATE

## Repeated Failures Captured
- Review REGRESSIONS.md and append any new "failure → guardrail" lines from today.

## Guardrails Added Today
- (autogenerated placeholder; fill from commit/review context)

## Evidence (last 24h commits)
$COMMITS

## Open Risks / Blockers Requiring Jon
- Missing health telemetry inputs for lifespan optimization (labs + wearable + protocol deltas)
- Missing App Store/Stripe read-only creds for real KPI reporting

## Next 24h Proactive Plan
1. Growth task with measurable awareness delta
2. Reliability hardening task
3. One autonomy change that removes a repeated ask
EOF

echo "self-improvement:ok:$OUT"
