#!/usr/bin/env bash
set -euo pipefail

WS="/home/jabbit/.openclaw/workspace"
DATE="$(date -u +%Y-%m-%d)"
OUT="$WS/docs/self-improvement-$DATE.md"

COMMITS=$(git -C "$WS" log --since='24 hours ago' --pretty=format:'- %h %s' | sed -n '1,20p' || true)

cat > "$OUT" <<EOF
# SELF-IMPROVEMENT LOG — $DATE

## Repeated Failures Captured
- Review REGRESSIONS.md and append any new "failure → guardrail" lines from today.

## Guardrails Added Today
- (autogenerated placeholder; fill from commit/review context)

## Evidence (last 24h commits)
$COMMITS

## 🔴 Self-Reflection: Impact on Jabbit Usage
Answer these 1x per week:
1. What tangible impact did our work have on driving Jabbit users/revenue this week?
2. What's actually moving the needle vs what just feels like "busy work"?
3. What's ONE thing we could do differently that would actually drive usage?
4. What blockers are keeping us from measuring real impact?

## Open Risks / Blockers Requiring Jon
- Missing health telemetry inputs for lifespan optimization (labs + wearable + protocol deltas)
- Missing App Store/Stripe read-only creds for real KPI reporting
- Reddit karma too low to start comment distribution
- No email capture on SEO pages

## Next 24h Proactive Plan
1. Growth task with measurable awareness delta
2. Reliability hardening task
3. One autonomy change that removes a repeated ask
EOF

echo "self-improvement:ok:$OUT"
